<?php $paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId()); ?>

<?= $block->escapeHtml($paymentTitle) ?>

<?php if ($block->getProvider()): ?>
    <table class="data-table admin__table-secondary">
        <tr>
            <th><?= __('Provider') ?>:</th>
            <td>
                <?= $block->getProvider() ?>
            </td>
        </tr>
        <tr>
            <th><?= __('Vendor') ?>:</th>
            <td>
                <?= $block->getVendor() ?>
            </td>
        </tr>
        <?php if ($block->getPspReference()): ?>
            <tr>
                <th><?= __('PSP Reference') ?>:</th>
                <td>
                    <?= $block->getPspReference() ?>
                </td>
            </tr>
        <?php endif ?>
        <?php if ($block->getMerchantReference()): ?>
            <tr>
                <th><?= __('Merchant Reference') ?>:</th>
                <td>
                    <?= $block->getMerchantReference() ?>
                </td>
            </tr>
        <?php endif ?>
    </table>
<?php endif ?>
